global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: 'nginx-metrics'
  #   static_configs:
  #     - targets: ['nginx:80']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121'] 

  - job_name: 'nginx-metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']